# Generated by Django 3.2.5 on 2021-08-15 09:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AracModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_tur', models.CharField(max_length=20)),
                ('arac_adi', models.CharField(max_length=20)),
                ('arac_marka', models.CharField(max_length=20)),
                ('arac_yakit', models.CharField(max_length=20)),
                ('arac_km_bilgisi', models.IntegerField(null=True)),
                ('arac_model', models.IntegerField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='arac_adi', unique=True)),
            ],
            options={
                'db_table': 'araclar',
            },
        ),
    ]
