# Generated by Django 3.2.5 on 2021-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aracmodel',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'Araç Bilgileri'},
        ),
        migrations.AddField(
            model_name='aracmodel',
            name='arac_plaka',
            field=models.IntegerField(null=True),
        ),
    ]
