# Generated by Django 3.2.5 on 2021-08-15 10:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ao', '0002_auto_20210815_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoforModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofor_resim', models.ImageField(upload_to='sofor_resimleri')),
                ('sofor_adi', models.CharField(max_length=50)),
                ('sofor_soyadi', models.CharField(max_length=50)),
                ('sofor_tel_no', models.IntegerField(null=True)),
                ('sofor_tc_kimlik_no', models.IntegerField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='sofor_adi', unique=True)),
                ('araclar', models.ManyToManyField(related_name='sofor', to='ao.AracModel')),
                ('sofor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soforler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sofor',
                'verbose_name_plural': 'soforler',
                'db_table': 'Sofor',
            },
        ),
    ]
