# Generated by Django 3.2.5 on 2021-08-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ao', '0003_soformodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soformodel',
            options={'verbose_name': 'Sofor', 'verbose_name_plural': 'Şoför Bilgileri'},
        ),
        migrations.CreateModel(
            name='MuayeneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periyodik_arac_bakim_tarihi', models.DateTimeField()),
                ('fren_sistemi_kontrol_tarihi', models.DateTimeField()),
                ('aku_degisim_tarihi', models.DateTimeField()),
                ('fren_hidroligi_degisim_tarihi', models.DateTimeField()),
                ('lastik_bakim_tarihi', models.DateTimeField()),
                ('amorsitor_bakim_tarihi', models.DateTimeField()),
                ('egzoz_kontrol_tarihi', models.DateTimeField()),
                ('yag_degisim_tarihi', models.DateTimeField()),
                ('araclar', models.ManyToManyField(related_name='muayene', to='ao.AracModel')),
                ('muayene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muayeneler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'muayeneler',
                'verbose_name_plural': 'Muayene Bilgileri',
                'db_table': 'muayene',
            },
        ),
    ]
