# Generated by Django 3.2.5 on 2021-08-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0004_auto_20210815_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofor_calisma_saatleri', models.TimeField()),
                ('arac_calisma_saatleri', models.TimeField()),
            ],
        ),
    ]
