# Generated by Django 3.2.5 on 2021-08-18 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ao', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iletisimmodel',
            options={'verbose_name': 'İletisim', 'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_plaka',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='GuzergahModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_guzergah_baslangic', models.CharField(max_length=50)),
                ('arac_guzergah_bitis', models.CharField(max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('araclar', models.ManyToManyField(related_name='guzergah', to='ao.AracModel')),
                ('guzergah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guzergahlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guzergah',
                'verbose_name_plural': 'Güzergahlar',
                'db_table': 'guzergah',
            },
        ),
    ]
