# Generated by Django 3.2.5 on 2021-08-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0007_auto_20210818_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guzergahmodel',
            old_name='arac_guzergah_baslangic',
            new_name='arac_guzergah',
        ),
        migrations.RenameField(
            model_name='guzergahmodel',
            old_name='arac_guzergah_bitis',
            new_name='arac_guzergah_baslangic_bitis',
        ),
    ]
