# Generated by Django 3.2.5 on 2021-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0008_auto_20210818_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('resim', models.ImageField(upload_to='')),
                ('isim_soyisim', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'profiller',
                'verbose_name_plural': 'Kullanıcı Bilgileri',
                'db_table': 'profil',
            },
        ),
        migrations.DeleteModel(
            name='MesaiModel',
        ),
    ]
