# Generated by Django 3.2.5 on 2021-08-28 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ao', '0009_auto_20210823_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmodel',
            name='araclar',
            field=models.ManyToManyField(blank=True, null=True, to='ao.AracModel'),
        ),
        migrations.AddField(
            model_name='profilmodel',
            name='deneme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilmodel',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilmodel',
            name='isim_soyisim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilmodel',
            name='kullanici_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilmodel',
            name='mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilmodel',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
