# Generated by Django 3.2.5 on 2021-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0011_auto_20210828_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muayenemodel',
            name='aku_degisim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='amorsitor_bakim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='egzoz_kontrol_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='fren_hidroligi_degisim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='fren_sistemi_kontrol_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='lastik_bakim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='periyodik_arac_bakim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muayenemodel',
            name='yag_degisim_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
