# Generated by Django 3.2.5 on 2021-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0012_auto_20210828_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_adi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_km_bilgisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_marka',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_model',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_plaka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_tur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aracmodel',
            name='arac_yakit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guzergahmodel',
            name='arac_guzergah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guzergahmodel',
            name='arac_guzergah_baslangic_bitis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guzergahmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
