# Generated by Django 3.2.5 on 2021-08-31 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ao', '0014_auto_20210828_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracmodel',
            name='arac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='araclar', to=settings.AUTH_USER_MODEL),
        ),
    ]
