# Generated by Django 3.2.6 on 2021-08-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0016_auto_20210831_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='soformodel',
            name='arac_cikis_saati',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='soformodel',
            name='arac_giris_saati',
            field=models.TimeField(null=True),
        ),
    ]
